# GitHub Actions workflow to automatically build and test Reposilite.
name: "Reposilite CI"

on:
  push:
    branches: [ "main", "3.0" ]
  pull_request:
    branches: [ "main", "3.0" ]

permissions:
  contents: read

jobs:
  build:
    name: "Build with JDK ${{ matrix.java-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Use 11 LTS releases and the latest one
        java-version: [ 17, 21 ]
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v6

    - name: "Fetch git tags" # Required for axion-release-plugin
      run: git fetch --tags --unshallow

    - name: "Validate gradle wrapper"
      uses: gradle/actions/wrapper-validation@v6

    - name: "Set up Java ${{ matrix.java-version }}"
      uses: actions/setup-java@v5
      with:
        java-version: "${{ matrix.java-version }}"
        distribution: "liberica"

    - name: "Grant execute permission for gradlew"
      run: chmod +x gradlew

    - name: "Set up Gradle"
      uses: gradle/actions/setup-gradle@v6

    - name: "Gradle build"
      run: ./gradlew :reposilite-backend:testCoverage

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v6
      with:
        files: "./reposilite-backend/build/reports/jacoco/reposilite-backend-report.xml"
        fail_ci_if_error: false
